source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'JKLValidator_Example', :exclusive => true do
  pod "JKLValidator", :path => "../"
end

target 'JKLValidator_Tests', :exclusive => true do
  pod "JKLValidator", :path => "../"

  pod 'Specta', '~> 1.0'
  pod 'Expecta',     '~> 1.0'   # expecta matchers
  # pod 'OCMockito',   '~> 1.0'   # OCMock
end
